use_frameworks!

target 'QXWADView_Example' do
  pod 'QXWADView', :path => '../'

  target 'QXWADView_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
